Fix: minikube

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -48,13 +48,13 @@ jobs:
       shell: powershell
       run: |
         if (!(winget list Kubernetes.minikube -q)) {
-          winget install --id Kubernetes.minikube -e --source winget
-          if ($LASTEXITCODE -ne 0) {
-          Write-Error "Failed to install Minikube."
-          exit 1
-          }
+            winget install --id Kubernetes.minikube -e --source winget
+            if ($LASTEXITCODE -ne 0) {
+                Write-Error "Failed to install Minikube."
+                exit 1
+            }
         } else {
-              Write-Host "Minikube is already installed. Skipping installation."
+            Write-Host "Minikube is already installed. Skipping installation."
         }
 
     # Step 7: Install kubectl
@@ -62,13 +62,13 @@ jobs:
       shell: pwsh
       run: |
         if (!(winget list Kubernetes.kubectl -q)) {
-          winget install --id Kubernetes.kubectl -e --source winget
-          if ($LASTEXITCODE -ne 0) {
-          Write-Error "Failed to install kubectl."
-          exit 1
+            winget install --id Kubernetes.kubectl -e --source winget
+            if ($LASTEXITCODE -ne 0) {
+                Write-Error "Failed to install kubectl."
+                exit 1
           }
         } else {
-        Write-Host "kubectl is already installed. Skipping installation."
+            Write-Host "kubectl is already installed. Skipping installation."
         }
 
     # Step 8: Start Minikube and configure kubectl
